name: Build Plugin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CMake build
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release

      - name: Move .vst3 file to win_vst3 folder (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p win_vst3
          find . -name "*.vst3" -exec mv {} win_vst3/ \;
      
      - name: Move .vst3 file to mac_vst3 folder (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p mac_vst3
          find . -name "*.vst3" -exec mv {} mac_vst3/ \;

      - name: Upload win_vst3 folder as artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: win_vst3
          path: win_vst3

      - name: Upload mac_vst3 folder as artifact (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: mac_vst3
          path: mac_vst3
